game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

error_page:
    path:     /error
    defaults: { _controller: GameBundle:Messages:error }

login:
    path:     /login
    defaults: { _controller: GameBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: GameBundle:User:logout }

registration:
    path:     /registration
    defaults: { _controller: GameBundle:User:registration }

submit_registration:
    path:     /submit_registration
    defaults: { _controller: GameBundle:User:submitRegistration }

character_overview:
    path:     /character
    defaults: { _controller: GameBundle:User:characterOverview }

create_character:
    path:     /create_character
    defaults: { _controller: GameBundle:User:createCharacter }

admin_console:
    path:     /admin
    defaults: { _controller: GameBundle:Admin:index }

admin_test:
    path:     /test
    defaults: { _controller: GameBundle:Admin:test }

map_view:
    path:     /mapview/{slug}
    defaults: { _controller: GameBundle:Mapview:index, slug: null }

get_map:
    path:   /map
    defaults: { _controller: GameBundle:Mapview:getMap }

get_entities:
    path:   /entities
    defaults: { _controller: GameBundle:Mapview:getEntities }

get_news:
    path:   /news
    defaults: { _controller: GameBundle:Mapview:getNews }
