game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: GameBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: GameBundle:User:logout }

registration:
    path:     /registration
    defaults: { _controller: GameBundle:User:registration }

submit_registration:
    path:     /submit_registration
    defaults: { _controller: GameBundle:User:submitRegistration }

admin_console:
    path:     /admin
    defaults: { _controller: GameBundle:Admin:index }

initialize_gameworld:
    path:     /newgame
    defaults: { _controller: GameBundle:Admin:newgame }