services:
  db:
    class: GameBundle\Game\DBCommon
    arguments: ["%database_host%", "%database_user%", "%database_password%", "%database_name%", "%database_port%"]

  service_login:
    class: GameBundle\Services\LoginService
    calls:
      - [setDb, ["@db"]]

  service_map:
    class: GameBundle\Services\MapService
    calls:
      - [setDb, ["@db"]]

  service_clan:
    class: GameBundle\Services\ClanService
    calls:
      - [setDb, ["@db"]]

  service_trade:
    class: GameBundle\Services\TradeService
    calls:
      - [setDb, ["@db"]]

  service_news:
    class: GameBundle\Services\NewsService
    calls:
      - [setDb, ["@db"]]

  service_tribe:
    class: GameBundle\Services\TribeService
    calls:
      - [setDb, ["@db"]]
      - [setMap, ["@service_map"]]

  service_rules:
    class: GameBundle\Game\Rules\Rules
    calls:
      - [setDb, ["@db"]]
      - [setMap, ["@service_map"]]

  service_action_round:
    class: GameBundle\Game\Simulation\ActionRound
    calls:
      - [setDb, ["@db"]]
      - [setBehavior, ["@service_behavior"]]
      - [setTribeService, ["@service_tribe"]]
      - [setMap, ["@service_map"]]
      - [setNews, ["@service_news"]]

  service_random_events:
    class: GameBundle\Game\Simulation\RandomEvents\RandomEvents
    calls:
      - [setDb, ["@db"]]
      - [setTrade, ["@service_trade"]]
      - [setMap, ["@service_map"]]
      - [setNews, ["@service_news"]]

  newgame:
    class: GameBundle\Game\Scenario\Newgame
    calls:
      - [setDb, ["@db"]]
      - [setMap, ["@service_map"]]
      - [setTribes, ["@service_tribe"]]
      - [setTrade, ["@service_trade"]]
      - [setEvents, ["@service_random_events"]]

  service_behavior:
    class: GameBundle\Game\Simulation\AI\Clans\Behavior
    calls:
      - [setDb, ["@db"]]
      - [setClans, ["@service_clan"]]
      - [setMap, ["@service_map"]]
      - [setNews, ["@service_news"]]
      - [setRules, ["@service_rules"]]
      - [setTribes, ["@service_tribe"]]
      - [setTrade, ["@service_trade"]]