services:
  db:
    class: GameBundle\Game\DBCommon
    arguments: ["%database_host%", "%database_user%", "%database_password%", "%database_name%", "%database_port%"]

  service_rules:
    class: GameBundle\Game\Rules\Rules
    calls:
      - [setDb, ["@db"]]

  service_login:
    class: GameBundle\Services\LoginService
    calls:
      - [setDb, ["@db"]]

  service_map:
    class: GameBundle\Services\MapService
    calls:
      - [setDb, ["@db"]]

  service_tribe:
    class: GameBundle\Services\TribeService
    calls:
      - [setDb, ["@db"]]

  service_news:
    class: GameBundle\Services\NewsService
    calls:
      - [setDb, ["db"]]

  service_newgame:
    class: GameBundle\Services\NewgameService
    calls:
      - [setDb, ["@db"]]

  service_actions:
    class: GameBundle\Game\Rules\Actions
    calls:
      - [setDb, ["@db"]]

  service_behavior:
    class: GameBundle\Game\Simulation\AI\Clans\Behavior
    calls:
      - [setDb, ["@db"]]
      - [setMap, ["@service_map"]]
      - [setNews, ["@service_news"]]
      - [setRules, ["@service_rules"]]
      - [setTribes, ["@service_tribe"]]

  service_action_round:
    class: GameBundle\Game\Simulation\ActionRound
    calls:
      - [setDb, ["@db"]]
      - [setBehavior, ["@service_behavior"]]
      - [setTribeService, ["@service_tribe"]]
      - [setMap, ["@service_map"]]
      - [setNews, ["@service_news"]]
