services:
    db:
        class: GameBundle\Game\DBCommon
        arguments: ["%database_host%", "%database_user%", "%database_password%", "%database_name%", "%database_port%"]
    service_login:
        class: GameBundle\Services\LoginService
        calls:
            - [setDb, ["@db"]]
    service_gameworld_admin:
        class: GameBundle\Services\GameworldAdminService
        calls:
            - [setDb, ["@db"]]