services:
    db:
        class: GameBundle\Game\DBCommon
        arguments: ["%database_host%", "%database_user%", "%database_password%", "%database_name%", "%database_port%"]
    service_login:
        class: GameBundle\Services\LoginService
        calls:
            - [setDb, ["@db"]]
    service_map:
        class: GameBundle\Services\MapService
        calls:
            - [setDb, ["@db"]]
    service_tribe:
        class: GameBundle\Services\TribeService
        calls:
            - [setDb, ["@db"]]
    dice:
        class: GameBundle\Game\Rules\Dice
        calls:
            - [setDb, ["@db"]]
    actions:
        class: GameBundle\Game\Rules\Actions
        calls:
            - [setDb, ["@db"]]
    service_newgame:
        class: GameBundle\Services\NewgameService
        calls:
            - [setDb, ["@db"]]