imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
               node: /usr/bin/node
               node_paths: [/usr/lib/node_modules]
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: ".less$"
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
        cssembed:
            jar: '%kernel.root_dir%/../vendor/scribe/cssembed-library/dist/cssembed.jar'
    assets:

            bootstrap_js:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
                filters: [?yui_js]
            bootstrap_less:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
                filters: [lessphp, cssembed]
            fonts_glyphicons_eot:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
                output: "fonts/glyphicons-halflings-regular.eot"
            fonts_glyphicons_svg:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
                output: "fonts/glyphicons-halflings-regular.svg"
            fonts_glyphicons_ttf:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
                output: "fonts/glyphicons-halflings-regular.ttf"
            fonts_glyphicons_woff:
                inputs:
                    - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"
                output: "fonts/glyphicons-halflings-regular.woff"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Mopa configuration
mopa_bootstrap:
    form: ~
    menu: ~